services:
#    huppys\CookieConsentBundle\:
#        resource: '../src/'

    huppys\CookieConsentBundle\Controller\:
        resource: '../src/Controller/*'
        public: true

    huppys\CookieConsentBundle\Cookie\CookieChecker:
        arguments: ["@=service('request_stack').getCurrentRequest()"]

    huppys\CookieConsentBundle\Cookie\CookieLogger:
        arguments:
            $request: "@=service('request_stack').getCurrentRequest()"
